title: Freshbits Blog
description: "Tips and Tutorials for the Developers."
keywords: "Jekyll, theme, SEO, blog, web"

url: "https://www.freshbits.in/blog"
baseurl: "/"
paginate_path: /page:num
gems: [jekyll-paginate]
paginate: 2

comments: true
disqus_shortname: "freshbitsblog"
subscribe: true

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: false
google-plus-share: true
tumblr-share: false
pinterest-share: false
